version: "3.5"

networks: 
  todo-network:
services:
  api:
    container_name: todo-api
    image: utainwp/todo-api
    networks: 
      - todo-network
  web:
    container_name: todo-web
    image: utainwp/todo-web
    ports: 
      - 80:80
      - 443:443
    links: 
      - api
    networks: 
      - todo-network