version: "3.5"

services:
  api:
    container_name: todo-api
    build: ../todo-service
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgres_connection_url
  web:
    container_name: todo-fe
    build: .
    ports: 
      - 80:80
      - 443:443
    environment: 
      - CI=true
      - REACT_VERSION=10
      - API_URL=http://api:8080/api
    volumes: 
      - ./:/app/
    links: 
      - api