FROM node:10.11-alpine

WORKDIR /app

ADD yarn.lock /app/yarn.lock
ADD package.json /app/package.json

ENV API_URL=http://localhost:8080/api
# ENV NODE_PATH=/node_modules
# ENV PATH=$PATH:/node_modules/.bin
RUN yarn

ADD . /app

EXPOSE 3000
EXPOSE 35729

CMD ["yarn", "start"]